version: "3.9"

services:
  web:
    image: php-apache-mysql:8.0-xdebug3.0
    container_name: servidor-web2
    ports:
      - 80:80
    volumes:
      - ./webapp:/var/www/html
    depends_on:
      - db
    networks:
      - default

  db:
    image: 'mysql'
    container_name: servidor-mysql2
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: quevedo
      MYSQL_DATABASE: quevedodb
      MYSQL_USER: quevedo
      MYSQL_PASSWORD: quevedo
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer
    container_name: adminer2
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
      - web
    networks:
      - default

networks:
  default:

volumes:
  webapp:
  db-data: